/**
 * E2E tests for `justin-sdk add husky`.
 *
 * These tests exercise the husky component installer. They don't run
 * `bun add` or `bun run prepare` (the installer only edits package.json
 * and writes the hook file), so they're fully offline and fast.
 */

import {describe, test, expect, afterEach} from 'bun:test';
import {existsSync, readFileSync, statSync, writeFileSync, mkdirSync} from 'fs';
import {join, resolve} from 'path';

import {
  POST_CHECKOUT_MARKER_BEGIN,
  POST_CHECKOUT_MARKER_END,
  composePostCheckout,
  readPostCheckoutPreamble,
  runHuskySetup,
} from '../src/husky-setup';
import {PINNED} from '../src/pinned-versions';
import {createProjectSandbox, type Sandbox} from './sandbox';

const sandboxes: Sandbox[] = [];

function track(sandbox: Sandbox): Sandbox {
  sandboxes.push(sandbox);
  return sandbox;
}

afterEach(() => {
  while (sandboxes.length > 0) {
    const sb = sandboxes.pop();
    sb?.cleanup();
  }
});

const TEMPLATE_PATH = resolve(
  import.meta.dirname,
  '..',
  'templates',
  'configs',
  '.husky',
  'pre-commit',
);

function readTemplate(): string {
  return readFileSync(TEMPLATE_PATH, 'utf-8');
}

/**
 * The version-manager hook line, verbatim from home-base's `.husky/post-checkout`
 * (2026-08-06). It is generated by version-manager's own `install-scripts`, so
 * the SDK must preserve it byte-for-byte rather than adopt or rewrite it
 * (home-base CLAUDE.md 2026-06-06, bead home-base-vhq.5).
 */
const VERSION_MANAGER_LINE =
  'npx @justinhaaheim/version-manager --git-hook || echo "WARNING: version-manager hook failed (non-fatal). If this is a fresh checkout/worktree, run \'bun install\'."';

function readPkg(sb: Sandbox): {
  devDependencies?: Record<string, string>;
  scripts?: Record<string, string>;
  ['lint-staged']?: Record<string, string[]>;
} {
  return JSON.parse(readFileSync(join(sb.path, 'package.json'), 'utf-8')) as {
    devDependencies?: Record<string, string>;
    scripts?: Record<string, string>;
    ['lint-staged']?: Record<string, string[]>;
  };
}

describe('husky-setup', () => {
  test('fresh project: writes devDeps, prepare, lint-staged config, and executable .husky/pre-commit', async () => {
    const sb = track(createProjectSandbox());

    const exitCode = await runHuskySetup({
      projectRoot: sb.path,
      quiet: true,
    });
    expect(exitCode).toBe(0);

    const pkg = readPkg(sb);

    // devDependencies at PINNED versions
    expect(pkg.devDependencies?.husky).toBe(PINNED.husky);
    expect(pkg.devDependencies?.['lint-staged']).toBe(PINNED['lint-staged']);

    // prepare script set to "husky"
    expect(pkg.scripts?.prepare).toBe('husky');

    // lint-staged config present
    expect(pkg['lint-staged']).toBeDefined();
    expect(pkg['lint-staged']?.['*.{ts,tsx,js,jsx,cjs,mjs}']).toEqual([
      'bun run lint-base -- --fix',
      'prettier --write',
    ]);
    expect(pkg['lint-staged']?.['*.{json,md,yml,yaml}']).toEqual([
      'prettier --write',
    ]);

    // .husky/pre-commit exists with template content
    const hookPath = join(sb.path, '.husky', 'pre-commit');
    expect(existsSync(hookPath)).toBe(true);
    expect(readFileSync(hookPath, 'utf-8')).toBe(readTemplate());

    // .husky/pre-commit is executable
    const mode = statSync(hookPath).mode;
    expect(mode & 0o111).not.toBe(0);

    // justin-sdk.config.json has husky-setup in components
    const config = JSON.parse(
      readFileSync(join(sb.path, 'justin-sdk.config.json'), 'utf-8'),
    ) as {components?: string[]};
    expect(config.components).toContain('husky-setup');
    expect(config.components).toContain('base-setup');
  });

  test('fully idempotent: second run produces same files', async () => {
    const sb = track(createProjectSandbox());

    const first = await runHuskySetup({projectRoot: sb.path, quiet: true});
    expect(first).toBe(0);

    const firstPkg = readFileSync(join(sb.path, 'package.json'), 'utf-8');
    const firstHook = readFileSync(
      join(sb.path, '.husky', 'pre-commit'),
      'utf-8',
    );

    const second = await runHuskySetup({projectRoot: sb.path, quiet: true});
    expect(second).toBe(0);

    expect(readFileSync(join(sb.path, 'package.json'), 'utf-8')).toBe(firstPkg);
    expect(readFileSync(join(sb.path, '.husky', 'pre-commit'), 'utf-8')).toBe(
      firstHook,
    );

    // No duplicate husky-setup entries
    const config = JSON.parse(
      readFileSync(join(sb.path, 'justin-sdk.config.json'), 'utf-8'),
    ) as {components?: string[]};
    const huskySetupCount = (config.components ?? []).filter(
      (c) => c === 'husky-setup',
    ).length;
    expect(huskySetupCount).toBe(1);
  });

  test('preserves user-customized "prepare" script', async () => {
    const sb = track(
      createProjectSandbox({
        packageJson: {
          name: 'test-project',
          scripts: {prepare: 'echo custom'},
        },
      }),
    );

    const exitCode = await runHuskySetup({
      projectRoot: sb.path,
      quiet: true,
    });
    expect(exitCode).toBe(0);

    const pkg = readPkg(sb);
    // User's custom prepare script preserved
    expect(pkg.scripts?.prepare).toBe('echo custom');
  });

  test('preserves user-customized lint-staged config', async () => {
    const customLintStaged = {
      '*.ts': ['my-custom-linter'],
    };
    const sb = track(
      createProjectSandbox({
        packageJson: {
          name: 'test-project',
          ['lint-staged']: customLintStaged,
        },
      }),
    );

    const exitCode = await runHuskySetup({
      projectRoot: sb.path,
      quiet: true,
    });
    expect(exitCode).toBe(0);

    const pkg = readPkg(sb);
    expect(pkg['lint-staged']).toEqual(customLintStaged);
  });

  test('preserves existing .husky/pre-commit content (warns, returns 0)', async () => {
    const sb = track(createProjectSandbox());
    // Pre-create a custom hook
    const customHook = '#!/usr/bin/env sh\necho my custom hook\n';
    mkdirSync(join(sb.path, '.husky'), {recursive: true});
    writeFileSync(join(sb.path, '.husky', 'pre-commit'), customHook);

    const exitCode = await runHuskySetup({
      projectRoot: sb.path,
      quiet: true,
    });
    expect(exitCode).toBe(0);

    // Custom hook preserved
    expect(readFileSync(join(sb.path, '.husky', 'pre-commit'), 'utf-8')).toBe(
      customHook,
    );
  });

  test('--force overwrites a hand-modified .husky/pre-commit', async () => {
    const sb = track(createProjectSandbox());
    mkdirSync(join(sb.path, '.husky'), {recursive: true});
    writeFileSync(
      join(sb.path, '.husky', 'pre-commit'),
      '#!/usr/bin/env sh\necho old hook\n',
    );

    const exitCode = await runHuskySetup({
      projectRoot: sb.path,
      quiet: true,
      force: true,
    });
    expect(exitCode).toBe(0);

    const hookPath = join(sb.path, '.husky', 'pre-commit');
    expect(readFileSync(hookPath, 'utf-8')).toBe(readTemplate());
    // Executable bit set
    expect(statSync(hookPath).mode & 0o111).not.toBe(0);
  });

  test('preserves a sibling hook in .husky/ (e.g., commit-msg)', async () => {
    const sb = track(createProjectSandbox());
    mkdirSync(join(sb.path, '.husky'), {recursive: true});
    const commitMsgContent =
      '#!/usr/bin/env sh\nnpx --no -- commitlint --edit "$1"\n';
    writeFileSync(join(sb.path, '.husky', 'commit-msg'), commitMsgContent);

    const exitCode = await runHuskySetup({
      projectRoot: sb.path,
      quiet: true,
    });
    expect(exitCode).toBe(0);

    // commit-msg preserved
    expect(readFileSync(join(sb.path, '.husky', 'commit-msg'), 'utf-8')).toBe(
      commitMsgContent,
    );
    // pre-commit written
    expect(readFileSync(join(sb.path, '.husky', 'pre-commit'), 'utf-8')).toBe(
      readTemplate(),
    );
  });

  test('preserves other devDependencies', async () => {
    const sb = track(
      createProjectSandbox({
        packageJson: {
          name: 'test-project',
          devDependencies: {someOther: '1.0.0'},
        },
      }),
    );

    const exitCode = await runHuskySetup({
      projectRoot: sb.path,
      quiet: true,
    });
    expect(exitCode).toBe(0);

    const pkg = readPkg(sb);
    expect(pkg.devDependencies?.someOther).toBe('1.0.0');
    expect(pkg.devDependencies?.husky).toBe(PINNED.husky);
    expect(pkg.devDependencies?.['lint-staged']).toBe(PINNED['lint-staged']);
  });

  test('preserves other scripts and adds prepare', async () => {
    const sb = track(
      createProjectSandbox({
        packageJson: {
          name: 'test-project',
          scripts: {build: 'echo build'},
        },
      }),
    );

    const exitCode = await runHuskySetup({
      projectRoot: sb.path,
      quiet: true,
    });
    expect(exitCode).toBe(0);

    const pkg = readPkg(sb);
    expect(pkg.scripts?.build).toBe('echo build');
    expect(pkg.scripts?.prepare).toBe('husky');
  });

  test('warns but does not overwrite existing husky devDependency at a different version', async () => {
    const sb = track(
      createProjectSandbox({
        packageJson: {
          name: 'test-project',
          devDependencies: {husky: '8.0.0'},
        },
      }),
    );

    const exitCode = await runHuskySetup({
      projectRoot: sb.path,
      quiet: true,
    });
    expect(exitCode).toBe(0);

    const pkg = readPkg(sb);
    expect(pkg.devDependencies?.husky).toBe('8.0.0');
    // lint-staged still added at pinned
    expect(pkg.devDependencies?.['lint-staged']).toBe(PINNED['lint-staged']);
  });

  test('--force overwrites existing devDependency versions', async () => {
    const sb = track(
      createProjectSandbox({
        packageJson: {
          name: 'test-project',
          devDependencies: {husky: '8.0.0', 'lint-staged': '13.0.0'},
        },
      }),
    );

    const exitCode = await runHuskySetup({
      projectRoot: sb.path,
      quiet: true,
      force: true,
    });
    expect(exitCode).toBe(0);

    const pkg = readPkg(sb);
    expect(pkg.devDependencies?.husky).toBe(PINNED.husky);
    expect(pkg.devDependencies?.['lint-staged']).toBe(PINNED['lint-staged']);
  });
});

/**
 * The managed `.husky/post-checkout` auto-hydration preamble (home-base-v170.12).
 *
 * These cover COMPOSITION — the three real input shapes and idempotency. That
 * the installed hook actually hydrates a fresh worktree is proven over real git
 * in tests/husky-post-checkout.test.ts.
 */
describe('husky-setup: .husky/post-checkout preamble', () => {
  /** home-base's hook verbatim as of 2026-08-06 — the block being superseded. */
  const HOME_BASE_LEGACY_HOOK = `# Dynamic version generator
# Fresh worktrees/clones have no node_modules yet, and version-manager lives
# there, so init submodules + install first; otherwise \`git worktree add\` /
# clone fail (missing deps, or an unresolved bun workspace from an
# uninitialized submodule). Skipped on normal branch switches (deps present).
[ -d node_modules ] || {
  echo "[post-checkout] Fresh checkout detected, initializing submodules + bun install..."
  [ -f .gitmodules ] && git submodule update --init --recursive
  bun install
}
${VERSION_MANAGER_LINE}
`;

  function preamble(): string {
    const text = readPostCheckoutPreamble();
    expect(text).not.toBeNull();
    return text as string;
  }

  function readHook(sb: Sandbox): string {
    return readFileSync(join(sb.path, '.husky', 'post-checkout'), 'utf-8');
  }

  test('fresh project: the preamble IS the hook, executable, marker-delimited', async () => {
    const sb = track(createProjectSandbox());

    expect(await runHuskySetup({projectRoot: sb.path, quiet: true})).toBe(0);

    const hook = readHook(sb);
    expect(hook).toBe(preamble());
    expect(hook).toContain(POST_CHECKOUT_MARKER_BEGIN);
    expect(hook).toContain(POST_CHECKOUT_MARKER_END);
    expect(hook).toContain('worktree-setup');
    expect(
      statSync(join(sb.path, '.husky', 'post-checkout')).mode & 0o111,
    ).not.toBe(0);
  });

  test('never installs a --native tier or a bare-name bunx invocation', () => {
    const hook = preamble();
    expect(hook).toContain(
      'bunx github:justinhaaheim/justin-sdk worktree-setup',
    );
    // Assert over the CODE only: both forbidden strings appear in the comments
    // that forbid them, so a whole-file match would pass vacuously.
    const code = hook
      .split('\n')
      .filter((line) => !line.trimStart().startsWith('#'))
      .join('\n');
    // NEVER --native from a hook: minutes of CocoaPods latency per worktree.
    expect(code).not.toContain('--native');
    // Bare-name bunx falls through to the npm registry (home-base-2qhw): the
    // static fallback must name its source explicitly.
    expect(code).not.toMatch(/bunx\s+justin-sdk/);
  });

  test('replaces home-base’s hand-rolled block, preserving the version-manager line byte-for-byte', async () => {
    const sb = track(createProjectSandbox());
    mkdirSync(join(sb.path, '.husky'), {recursive: true});
    writeFileSync(
      join(sb.path, '.husky', 'post-checkout'),
      HOME_BASE_LEGACY_HOOK,
    );

    expect(await runHuskySetup({projectRoot: sb.path, quiet: true})).toBe(0);

    const hook = readHook(sb);
    // The hand-rolled hydration is gone — worktree-setup does all of it now.
    expect(hook).not.toContain('git submodule update --init --recursive');
    expect(hook).not.toContain('initializing submodules + bun install');
    expect(hook).not.toContain('# Fresh worktrees/clones have no node_modules');
    // version-manager owns its own line; it survives verbatim …
    expect(hook).toContain(VERSION_MANAGER_LINE);
    // … below the managed block, so hydration happens BEFORE it needs deps.
    expect(hook.indexOf(POST_CHECKOUT_MARKER_END)).toBeLessThan(
      hook.indexOf(VERSION_MANAGER_LINE),
    );
    // The comment describing the version-manager line stays with it; only the
    // comments describing the removed block go.
    expect(hook).toContain('# Dynamic version generator');
  });

  test('a hook holding only the version-manager line keeps it, unchanged', () => {
    const existing = `${VERSION_MANAGER_LINE}\n`;
    const composed = composePostCheckout(existing, preamble());
    if (composed.kind !== 'inserted') {
      throw new Error(`expected an insert, got ${composed.kind}`);
    }
    // Nothing legacy to strip — this hook only ever had the one line.
    expect(composed.legacyStripped).toBe(false);
    expect(composed.content).toContain(VERSION_MANAGER_LINE);
    expect(composed.content.startsWith(POST_CHECKOUT_MARKER_BEGIN)).toBe(true);
  });

  test('idempotent: a re-install rewrites the block in place, never duplicates it', async () => {
    const sb = track(createProjectSandbox());

    expect(await runHuskySetup({projectRoot: sb.path, quiet: true})).toBe(0);
    const first = readHook(sb);
    expect(await runHuskySetup({projectRoot: sb.path, quiet: true})).toBe(0);
    expect(readHook(sb)).toBe(first);

    const markerCount = (hook: string): number =>
      hook.split('\n').filter((l) => l.startsWith(POST_CHECKOUT_MARKER_BEGIN))
        .length;
    expect(markerCount(readHook(sb))).toBe(1);
  });

  test('a stale managed block is UPDATED in place, leaving surrounding lines alone', () => {
    const stale = [
      '# project-owned line above',
      `${POST_CHECKOUT_MARKER_BEGIN} >>>`,
      'echo "an older SDK version did it this way"',
      `${POST_CHECKOUT_MARKER_END} <<<`,
      '# project-owned line below',
      VERSION_MANAGER_LINE,
      '',
    ].join('\n');

    const composed = composePostCheckout(stale, preamble());
    expect(composed.kind).toBe('replaced');
    if (!('content' in composed)) throw new Error('no content');
    expect(composed.content).not.toContain('an older SDK version');
    expect(composed.content).toContain('# project-owned line above');
    expect(composed.content).toContain('# project-owned line below');
    expect(composed.content).toContain(VERSION_MANAGER_LINE);
    // Second pass is a no-op — the update converges.
    expect(composePostCheckout(composed.content, preamble()).kind).toBe(
      'unchanged',
    );
  });

  test('a shebang stays the first line', () => {
    const composed = composePostCheckout(
      `#!/usr/bin/env sh\n${VERSION_MANAGER_LINE}\n`,
      preamble(),
    );
    if (!('content' in composed)) throw new Error('no content');
    expect(composed.content.split('\n')[0]).toBe('#!/usr/bin/env sh');
    expect(composed.content.split('\n')[1]).toStartWith(
      POST_CHECKOUT_MARKER_BEGIN,
    );
  });

  test('a hand-truncated block is refused, not guessed at', async () => {
    const mangled = `${POST_CHECKOUT_MARKER_BEGIN} >>>\necho "half a block"\n${VERSION_MANAGER_LINE}\n`;
    expect(composePostCheckout(mangled, preamble())).toEqual({
      kind: 'unterminated',
    });

    // …and the installer leaves the file alone while still exiting 0, so one
    // mangled hook cannot block `add husky` in a project.
    const sb = track(createProjectSandbox());
    mkdirSync(join(sb.path, '.husky'), {recursive: true});
    writeFileSync(join(sb.path, '.husky', 'post-checkout'), mangled);
    expect(await runHuskySetup({projectRoot: sb.path, quiet: true})).toBe(0);
    expect(readHook(sb)).toBe(mangled);
  });
});
