/**
 * Tests for the sweep's PIN WRITE — home-base-apus.1.
 *
 * THE CONTRACT UNDER TEST: after the pin step, package.json declares
 * `@justinhaaheim/justin-sdk` EXACTLY ONCE, in devDependencies, at the swept
 * pin — from any of the four manifest shapes the fleet actually holds — and a
 * repo whose SDK comes from a WORKSPACE MEMBER gets no pin written at all.
 *
 * WHY THESE RUN THE REAL PACKAGE MANAGERS. Every bug this fixes is a bug in
 * what `bun`/`npm`/`yarn` DO to a manifest, not in what this module believes
 * they do. A faked runner would have asserted my model of bun and passed while
 * the fleet burned — the maiden real sweep took 4 of its first 6 repos red on
 * exactly such an assumption. So the fixtures shell out for real.
 *
 * WHY THE PIN IS A `file:` SPEC HERE. Real managers, no network: the pin string
 * is a parameter of `writeSdkPin`, so a local fixture package stands in for the
 * github spec. What that costs is stated plainly rather than papered over — the
 * `DependencyLoop` arm is github-resolution-shaped and CANNOT be reproduced
 * offline. Its measurement lives on home-base-apus.1 (verbatim error, four
 * arms) and its real proof is the fleet re-sweep, where every repo that failed
 * has precisely that shape. What the `file:` pin DOES reproduce offline is the
 * same precondition — "the package is already declared at a different spec" —
 * and bun's other, quieter answer to it: the same key written twice into one
 * object.
 */

import {afterEach, describe, expect, test} from 'bun:test';
import {execFileSync} from 'child_process';
import {mkdirSync, readFileSync, writeFileSync} from 'fs';
import {join} from 'path';

import {
  countSdkKeyDeclarations,
  readSdkDeclarations,
  runSweep,
  sdkWorkspaceSatisfaction,
  verifySinglePin,
  workspacePatternsOf,
  writeSdkPin,
  type DepSection,
} from '../src/sweep';
import {initRepo} from './git-fixtures';
import {createSandbox, type Sandbox} from './sandbox';

const SDK_PKG = '@justinhaaheim/justin-sdk';

const sandboxes: Sandbox[] = [];
function track(sb: Sandbox): Sandbox {
  sandboxes.push(sb);
  return sb;
}
afterEach(() => {
  while (sandboxes.length > 0) sandboxes.pop()?.cleanup();
});

// ---------------------------------------------------------------------------
// Fixtures
// ---------------------------------------------------------------------------

type Manager = 'bun' | 'npm' | 'yarn';

interface PinFixture {
  root: string;
  pkgPath: string;
  /** The pin `writeSdkPin` is asked to land. */
  newPin: string;
  /** The stale spec the fixture starts out declaring. */
  oldPin: string;
  read: () => string;
}

function writePkg(path: string, pkg: unknown): void {
  writeFileSync(path, `${JSON.stringify(pkg, null, 2)}\n`);
}

/**
 * A repo declaring the SDK in `sections`, at a stale local spec, with a
 * lockfile of the right flavour so detectPackageManager picks `manager`.
 *
 * The lockfile is generated by really running `<manager> install`, not stubbed:
 * `yarn remove` HARD-FAILS without one ("error No lockfile in this directory"),
 * which is a real behaviour the pin step has to survive rather than a detail to
 * fake away.
 */
function pinFixture(options: {
  manager?: Manager;
  sections?: readonly DepSection[];
  install?: boolean;
}): PinFixture {
  const manager = options.manager ?? 'bun';
  const sections = options.sections ?? ['devDependencies'];
  const install = options.install ?? true;

  const sb = track(createSandbox());
  // Two stand-in SDK packages so "old spec" and "new spec" are genuinely
  // different resolutions, exactly as two github commits would be.
  for (const [dir, version] of [
    ['sdk-old', '0.0.1'],
    ['sdk-new', '0.0.2'],
  ] as const) {
    mkdirSync(join(sb.path, dir), {recursive: true});
    writePkg(join(sb.path, dir, 'package.json'), {name: SDK_PKG, version});
  }

  const root = join(sb.path, 'repo');
  mkdirSync(root, {recursive: true});
  const oldPin = 'file:../sdk-old';
  const newPin = 'file:../sdk-new';

  const pkg: Record<string, unknown> = {name: 'fixture', version: '0.0.1'};
  for (const section of sections) pkg[section] = {[SDK_PKG]: oldPin};
  const pkgPath = join(root, 'package.json');
  writePkg(pkgPath, pkg);

  if (install) {
    // Quiet, offline: a file: dependency never reaches a registry.
    execFileSync(manager, ['install'], {cwd: root, stdio: 'ignore'});
  } else if (manager !== 'bun') {
    throw new Error('install:false only makes sense for the bun fixture');
  }

  return {
    newPin,
    oldPin,
    pkgPath,
    read: () => readFileSync(pkgPath, 'utf-8'),
    root,
  };
}

/** Parsed declarations of a fixture, as a plain object for readable asserts. */
function declarationsOf(root: string): Record<string, string> {
  const result = readSdkDeclarations(root);
  if (!result.ok) throw new Error(`unreadable fixture: ${result.reason}`);
  return Object.fromEntries(result.declared);
}

// ---------------------------------------------------------------------------
// readSdkDeclarations
// ---------------------------------------------------------------------------

describe('readSdkDeclarations', () => {
  test('reports each section that declares the SDK, with its spec', () => {
    const fixture = pinFixture({
      install: false,
      sections: ['dependencies', 'devDependencies'],
    });
    expect(declarationsOf(fixture.root)).toEqual({
      dependencies: fixture.oldPin,
      devDependencies: fixture.oldPin,
    });
  });

  test('a manifest declaring the SDK nowhere reads as an empty map, not a failure', () => {
    const fixture = pinFixture({install: false, sections: []});
    const result = readSdkDeclarations(fixture.root);
    expect(result.ok).toBe(true);
    if (!result.ok) throw new Error('unreachable');
    expect([...result.declared.keys()]).toEqual([]);
  });

  test('RULE 5: an unreadable package.json is a failure, NOT "declared nowhere"', () => {
    // The whole fix hangs off this distinction. "Declared nowhere" is the
    // verdict that skips the remove — so a package.json this cannot parse must
    // never be able to produce it, or a stale declaration survives the write.
    const fixture = pinFixture({install: false, sections: ['devDependencies']});
    writeFileSync(fixture.pkgPath, '{ this is not json');
    const result = readSdkDeclarations(fixture.root);
    expect(result.ok).toBe(false);
    if (result.ok) throw new Error('unreachable');
    expect(result.reason).toContain('package.json');
  });

  test('a missing package.json is a failure too', () => {
    const sb = track(createSandbox());
    const result = readSdkDeclarations(sb.path);
    expect(result.ok).toBe(false);
    if (result.ok) throw new Error('unreachable');
    expect(result.reason).toContain('not found');
  });
});

// ---------------------------------------------------------------------------
// countSdkKeyDeclarations
// ---------------------------------------------------------------------------

describe('countSdkKeyDeclarations', () => {
  test('counts declarations, not mentions — a script alias naming the SDK is not one', () => {
    const text = JSON.stringify(
      {
        devDependencies: {[SDK_PKG]: 'github:justinhaaheim/justin-sdk#v1.0.0'},
        scripts: {
          doctor: `bunx ${SDK_PKG} doctor`,
          signal: `bunx ${SDK_PKG} signal`,
        },
      },
      null,
      2,
    );
    expect(countSdkKeyDeclarations(text)).toBe(1);
  });

  test('sees the duplicate KEY that JSON.parse hides', () => {
    // Hand-written because JSON.stringify cannot express it — which is the
    // point: this shape is unreachable from any parsed view of the manifest.
    const text = [
      '{',
      '  "devDependencies": {',
      `    "${SDK_PKG}": "file:../sdk-old",`,
      `    "${SDK_PKG}": "file:../sdk-new"`,
      '  }',
      '}',
    ].join('\n');
    expect(countSdkKeyDeclarations(text)).toBe(2);
    // …and the parsed view does NOT — the negative control for this function's
    // existence.
    const parsed = JSON.parse(text) as {
      devDependencies: Record<string, string>;
    };
    expect(Object.keys(parsed.devDependencies)).toHaveLength(1);
  });

  test('zero when the SDK is not declared at all', () => {
    expect(countSdkKeyDeclarations('{"name":"x"}')).toBe(0);
  });
});

// ---------------------------------------------------------------------------
// verifySinglePin
// ---------------------------------------------------------------------------

describe('verifySinglePin', () => {
  const PIN = 'github:justinhaaheim/justin-sdk#v0.18.1';
  const map = (
    entries: Record<string, string>,
  ): ReadonlyMap<DepSection, string> =>
    new Map(Object.entries(entries) as Array<[DepSection, string]>);

  test('exactly one devDependencies declaration at the pin is the contract', () => {
    expect(verifySinglePin(map({devDependencies: PIN}), PIN)).toEqual({
      ok: true,
    });
  });

  test('two declarations fail, and the reason names both', () => {
    const result = verifySinglePin(
      map({
        dependencies: 'github:justinhaaheim/justin-sdk#v0.9.0',
        devDependencies: PIN,
      }),
      PIN,
    );
    expect(result.ok).toBe(false);
    if (result.ok) throw new Error('unreachable');
    expect(result.reason).toContain('v0.9.0');
    expect(result.reason).toContain(PIN);
  });

  test('the right pin in the wrong section fails (the yarn shape)', () => {
    const result = verifySinglePin(map({dependencies: PIN}), PIN);
    expect(result.ok).toBe(false);
    if (result.ok) throw new Error('unreachable');
    expect(result.reason).toContain('dependencies');
  });

  test('the right section at the wrong spec fails', () => {
    const result = verifySinglePin(
      map({devDependencies: 'github:justinhaaheim/justin-sdk#v0.9.0'}),
      PIN,
    );
    expect(result.ok).toBe(false);
    if (result.ok) throw new Error('unreachable');
    expect(result.reason).toContain('not the swept pin');
  });

  test('no declaration at all fails — a vanished pin is not a clean pin', () => {
    const result = verifySinglePin(map({}), PIN);
    expect(result.ok).toBe(false);
    if (result.ok) throw new Error('unreachable');
    expect(result.reason).toContain('neither');
  });
});

// ---------------------------------------------------------------------------
// Workspace satisfaction (t6a0.21 D21)
// ---------------------------------------------------------------------------

describe('workspacePatternsOf', () => {
  test('the array shape', () => {
    expect(workspacePatternsOf({workspaces: ['projects/justin-sdk']})).toEqual([
      'projects/justin-sdk',
    ]);
  });

  test('the {packages: []} shape', () => {
    expect(
      workspacePatternsOf({workspaces: {packages: ['packages/*']}}),
    ).toEqual(['packages/*']);
  });

  test('no workspaces, and non-string entries, contribute nothing', () => {
    expect(workspacePatternsOf({name: 'x'})).toEqual([]);
    expect(workspacePatternsOf({workspaces: [1, 'ok', null]})).toEqual(['ok']);
  });
});

describe('sdkWorkspaceSatisfaction', () => {
  test('a `workspace:` spec on the declaration is enough — home-base’s shape', () => {
    const sb = track(createSandbox());
    writePkg(join(sb.path, 'package.json'), {
      dependencies: {[SDK_PKG]: 'workspace:*'},
      name: 'home-base-like',
      workspaces: ['projects/justin-sdk'],
    });
    const result = sdkWorkspaceSatisfaction(
      sb.path,
      new Map<DepSection, string>([['dependencies', 'workspace:*']]),
    );
    expect(result.satisfied).toBe(true);
    if (!result.satisfied) throw new Error('unreachable');
    expect(result.reason).toContain('workspace:*');
  });

  test('a workspaces MEMBER that IS the SDK is enough on its own', () => {
    // The belt to the `workspace:` spec’s braces: a repo resolving the SDK
    // through its workspaces array without the `workspace:` protocol.
    const sb = track(createSandbox());
    mkdirSync(join(sb.path, 'projects', 'justin-sdk'), {recursive: true});
    writePkg(join(sb.path, 'projects', 'justin-sdk', 'package.json'), {
      name: SDK_PKG,
      version: '0.18.1',
    });
    writePkg(join(sb.path, 'package.json'), {
      dependencies: {[SDK_PKG]: '*'},
      name: 'home-base-like',
      workspaces: ['projects/justin-sdk'],
    });
    const result = sdkWorkspaceSatisfaction(
      sb.path,
      new Map<DepSection, string>([['dependencies', '*']]),
    );
    expect(result.satisfied).toBe(true);
    if (!result.satisfied) throw new Error('unreachable');
    expect(result.reason).toContain('projects/justin-sdk');
  });

  test('a `packages/*` pattern is expanded', () => {
    const sb = track(createSandbox());
    mkdirSync(join(sb.path, 'packages', 'sdk'), {recursive: true});
    writePkg(join(sb.path, 'packages', 'sdk', 'package.json'), {name: SDK_PKG});
    mkdirSync(join(sb.path, 'packages', 'other'), {recursive: true});
    writePkg(join(sb.path, 'packages', 'other', 'package.json'), {
      name: 'other',
    });
    writePkg(join(sb.path, 'package.json'), {
      name: 'monorepo',
      workspaces: ['packages/*'],
    });
    expect(sdkWorkspaceSatisfaction(sb.path, new Map()).satisfied).toBe(true);
  });

  test('an ORDINARY pinned repo is not workspace-satisfied — the guard must not swallow the fleet', () => {
    // Without this, "skip the pin" would apply to all 11 pin consumers and the
    // sweep would silently stop bumping anything.
    const fixture = pinFixture({install: false});
    const declared = readSdkDeclarations(fixture.root);
    if (!declared.ok) throw new Error('unreachable');
    expect(
      sdkWorkspaceSatisfaction(fixture.root, declared.declared).satisfied,
    ).toBe(false);
  });
});

// ---------------------------------------------------------------------------
// writeSdkPin against the REAL package managers — AC1-AC4
// ---------------------------------------------------------------------------

describe('writeSdkPin — bun, every fleet manifest shape (AC1-AC3)', () => {
  test('devDependencies at an OLD spec: the pin lands, exactly once (AC1 shape)', () => {
    const fixture = pinFixture({sections: ['devDependencies']});
    const result = writeSdkPin(fixture.root, fixture.newPin);
    expect(result.ok).toBe(true);
    if (!result.ok) throw new Error(result.detail);
    expect(declarationsOf(fixture.root)).toEqual({
      devDependencies: fixture.newPin,
    });
    expect(countSdkKeyDeclarations(fixture.read())).toBe(1);
  });

  test('NEGATIVE CONTROL: `bun add -d` over that same fixture writes the key TWICE', () => {
    // The offline face of the bug. With a GITHUB spec this same precondition
    // produces the `DependencyLoop` that stopped the maiden sweep (measured on
    // home-base-apus.1, four arms); with a `file:` spec bun instead corrupts
    // the manifest with a duplicate key. Same precondition, same fix, and this
    // arm is the one that can be automated.
    const fixture = pinFixture({sections: ['devDependencies']});
    execFileSync('bun', ['add', '-d', fixture.newPin], {
      cwd: fixture.root,
      stdio: 'ignore',
    });
    expect(countSdkKeyDeclarations(fixture.read())).toBe(2);
  });

  test('dependencies only: normalized into devDependencies, exactly once (AC2)', () => {
    const fixture = pinFixture({sections: ['dependencies']});
    const result = writeSdkPin(fixture.root, fixture.newPin);
    expect(result.ok).toBe(true);
    if (!result.ok) throw new Error(result.detail);
    expect(declarationsOf(fixture.root)).toEqual({
      devDependencies: fixture.newPin,
    });
    expect(countSdkKeyDeclarations(fixture.read())).toBe(1);
    // The normalization is REPORTED, not silent — it changes the manifest’s
    // shape, so it has to be visible in the sweep summary.
    expect(result.summaryNote).toContain('dependencies → devDependencies');
  });

  test('NEGATIVE CONTROL: `bun add -d` over that same fixture leaves TWO declarations', () => {
    // health-logger-rn d14c327, committed and pushed: `dependencies` #v0.9.0
    // beside `devDependencies` #v0.18.0.
    const fixture = pinFixture({sections: ['dependencies']});
    execFileSync('bun', ['add', '-d', fixture.newPin], {
      cwd: fixture.root,
      stdio: 'ignore',
    });
    expect(declarationsOf(fixture.root)).toEqual({
      dependencies: fixture.oldPin,
      devDependencies: fixture.newPin,
    });
  });

  test('BOTH sections (the ynab-mcp-deluxe shape): ends with exactly one (AC3)', () => {
    const fixture = pinFixture({
      sections: ['dependencies', 'devDependencies'],
    });
    const result = writeSdkPin(fixture.root, fixture.newPin);
    expect(result.ok).toBe(true);
    if (!result.ok) throw new Error(result.detail);
    expect(declarationsOf(fixture.root)).toEqual({
      devDependencies: fixture.newPin,
    });
    expect(countSdkKeyDeclarations(fixture.read())).toBe(1);
  });

  test('NEGATIVE CONTROL: `bun add -d` over the both-sections fixture leaves two', () => {
    const fixture = pinFixture({
      sections: ['dependencies', 'devDependencies'],
    });
    execFileSync('bun', ['add', '-d', fixture.newPin], {
      cwd: fixture.root,
      stdio: 'ignore',
    });
    expect(Object.keys(declarationsOf(fixture.root)).sort()).toEqual([
      'dependencies',
      'devDependencies',
    ]);
  });

  test('a repo declaring the SDK nowhere still gets the pin', () => {
    // The enrollment path: nothing to remove, the add is the whole step.
    const fixture = pinFixture({sections: []});
    const result = writeSdkPin(fixture.root, fixture.newPin);
    expect(result.ok).toBe(true);
    if (!result.ok) throw new Error(result.detail);
    expect(declarationsOf(fixture.root)).toEqual({
      devDependencies: fixture.newPin,
    });
    expect(result.summaryNote).toBeUndefined();
  });
});

describe('writeSdkPin — npm and yarn (AC4)', () => {
  test('npm: a `dependencies` declaration is normalized into devDependencies', () => {
    const fixture = pinFixture({manager: 'npm', sections: ['dependencies']});
    const result = writeSdkPin(fixture.root, fixture.newPin);
    expect(result.ok).toBe(true);
    if (!result.ok) throw new Error(result.detail);
    expect(declarationsOf(fixture.root)).toEqual({
      devDependencies: fixture.newPin,
    });
  });

  test('yarn: same, and the remove is what makes it true', () => {
    const fixture = pinFixture({manager: 'yarn', sections: ['dependencies']});
    const result = writeSdkPin(fixture.root, fixture.newPin);
    expect(result.ok).toBe(true);
    if (!result.ok) throw new Error(result.detail);
    expect(declarationsOf(fixture.root)).toEqual({
      devDependencies: fixture.newPin,
    });
  });

  test('NEGATIVE CONTROL: `yarn add --dev` alone updates the spec IN `dependencies`', () => {
    // yarn’s own failure mode, and the reason the remove is not npm-only
    // ceremony: the `--dev` is silently ignored for an already-declared
    // package, so the SDK would stay a runtime dependency forever.
    const fixture = pinFixture({manager: 'yarn', sections: ['dependencies']});
    execFileSync('yarn', ['add', '--dev', fixture.newPin], {
      cwd: fixture.root,
      stdio: 'ignore',
    });
    expect(declarationsOf(fixture.root)).toEqual({
      dependencies: fixture.newPin,
    });
  });

  test('a failing ADD is reported red, and the manifest is left declaring nothing rather than something wrong', () => {
    // The one cost of remove-then-add: between the two commands the repo
    // declares no SDK at all. That window is safe by construction — a red
    // payload returns before the sweep's commit step, so this state can only
    // ever be seen in a standing worktree — but the failure has to be LOUD, or
    // "the pin did not land" becomes indistinguishable from "already current".
    //
    // (The other failure this guard covers, a red REMOVE, is not reachable
    // through the sweep for yarn the way it first appeared: `yarn remove`
    // errors "No lockfile in this directory", but detectPackageManager only
    // selects yarn BECAUSE a yarn.lock exists — and an empty one satisfies
    // yarn. Measured, rather than assumed from the error text.)
    const fixture = pinFixture({sections: ['devDependencies']});
    const result = writeSdkPin(fixture.root, 'file:../no-such-package');
    expect(result.ok).toBe(false);
    if (result.ok) throw new Error('unreachable');
    expect(result.detail).toContain('bun add');
    expect(declarationsOf(fixture.root)).toEqual({});
  });
});

describe('writeSdkPin — the workspace consumer (D21)', () => {
  function homeBaseLike(): {root: string; read: () => string} {
    const sb = track(createSandbox());
    const root = join(sb.path, 'repo');
    mkdirSync(join(root, 'projects', 'justin-sdk'), {recursive: true});
    writePkg(join(root, 'projects', 'justin-sdk', 'package.json'), {
      name: SDK_PKG,
      version: '0.18.1',
    });
    mkdirSync(join(sb.path, 'sdk-new'), {recursive: true});
    writePkg(join(sb.path, 'sdk-new', 'package.json'), {name: SDK_PKG});
    writePkg(join(root, 'package.json'), {
      dependencies: {[SDK_PKG]: 'workspace:*'},
      name: 'home-base-like',
      version: '0.0.1',
      workspaces: ['projects/justin-sdk'],
    });
    return {
      read: () => readFileSync(join(root, 'package.json'), 'utf-8'),
      root,
    };
  }

  test('the pin is NOT written, the manifest is byte-identical, and the skip is REPORTED', () => {
    const project = homeBaseLike();
    const before = project.read();

    const result = writeSdkPin(project.root, 'file:../sdk-new');

    expect(result.ok).toBe(true);
    if (!result.ok) throw new Error(result.detail);
    expect(project.read()).toBe(before);
    // Never silent, never conflated with "pinned" (D21).
    expect(result.note).toContain('workspace-satisfied');
    expect(result.summaryNote).toBe('pin: workspace-satisfied, not written');
  });

  test('NEGATIVE CONTROL: the un-skipped write converts it to a github-pin consumer', () => {
    // What a full sweep of home-base did before D21 — and it would have gone
    // GREEN: a second declaration beside `workspace:*`, on the repo that hosts
    // the SDK’s own development loop.
    const project = homeBaseLike();
    execFileSync('bun', ['add', '-d', 'file:../sdk-new'], {
      cwd: project.root,
      stdio: 'ignore',
    });
    const declared = declarationsOf(project.root);
    expect(declared.dependencies).toBe('workspace:*');
    expect(declared.devDependencies).toBe('file:../sdk-new');
  });
});

// ---------------------------------------------------------------------------
// The dry-run plan has to SAY it, before the real run
// ---------------------------------------------------------------------------

describe('runSweep --dry-run names the repo that will not be pinned', () => {
  async function captureLog<T>(fn: () => Promise<T>): Promise<string> {
    const original = console.log;
    let out = '';
    console.log = (...args: unknown[]) => {
      out += `${args.join(' ')}\n`;
    };
    try {
      await fn();
    } finally {
      console.log = original;
    }
    return out;
  }

  test('a workspace consumer is flagged in the plan; a pinned repo is not', async () => {
    // The plan is what an operator reads BEFORE authorizing a fleet-wide run
    // that commits and pushes. "would sweep off main" is the same line for a
    // repo that gets a pin bump and for one that structurally cannot — so the
    // difference has to be on the plan line itself.
    const sb = track(createSandbox());
    const pinned = initRepo(sb, 'pinned', {
      'justin-sdk.config.json': `${JSON.stringify({components: ['base-setup']}, null, 2)}\n`,
      'package.json': `${JSON.stringify(
        {
          devDependencies: {
            [SDK_PKG]: 'github:justinhaaheim/justin-sdk#v0.9.0',
          },
          name: 'pinned',
          version: '0.0.1',
        },
        null,
        2,
      )}\n`,
    });
    const workspace = initRepo(sb, 'workspace-consumer', {
      'justin-sdk.config.json': `${JSON.stringify({components: ['base-setup']}, null, 2)}\n`,
      'package.json': `${JSON.stringify(
        {
          dependencies: {[SDK_PKG]: 'workspace:*'},
          name: 'workspace-consumer',
          version: '0.0.1',
          workspaces: ['projects/justin-sdk'],
        },
        null,
        2,
      )}\n`,
    });

    const out = await captureLog(() =>
      runSweep({dryRun: true, repos: [pinned, workspace]}),
    );

    // Strip the summary's own SGR codes so the assertion is about words.
    const plain = out.replace(/\x1b\[[0-9;]*m/g, '');
    const lineFor = (name: string): string =>
      plain.split('\n').find((line) => line.trim().startsWith(`= ${name} `)) ??
      '';

    expect(lineFor('workspace-consumer')).toContain(
      'would sweep off main — pin: workspace-satisfied, would NOT be written',
    );
    // The ordinary repo's line is unchanged — the flag is not decoration.
    expect(lineFor('pinned').trim()).toBe('= pinned would sweep off main');
  });
});
